# Generated by Django 4.1.7 on 2023-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=20)),
                ('batch', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('PROEmail', models.CharField(max_length=20, null=True)),
                ('OFFEmail', models.CharField(max_length=20, null=True)),
                ('contact_no', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('domain', models.CharField(max_length=15, null=True)),
                ('willing_contribution', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
