# Generated by Django 4.1.7 on 2023-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='id',
        ),
        migrations.AddField(
            model_name='alumni',
            name='sl_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
